### ISSUE TITLE
add new fields to Your License 

### ISSUE THREAD

**Issue by kellyhiser** [therabble/nashville-public-library-client#14]
- [ ] Required: "Tax ID or Social Security Number" number value 
- [ ] Optional: "Songwriters" allow multiple inputs separated by commas

Both of these should populate proper place on the license: https://drive.google.com/file/d/0B1G7kY2BmLkGNXZjVTRncFliWFE/view

**Comment by whblondeau** [comment]
Fields are added to app/templates/admin/complete-submission/license.hbs.

Still need to make sure they get into the models.

**Comment by whblondeau** [comment]
Currently studying /app/models/contract.js. Definitely stuff in there.
