### ISSUE TITLE
card authentication directions

### ISSUE THREAD

**Issue by kellyhiser** [therabble/nashville-public-library-client#17]
this all from James Staub, in email:

[1 is irrelevant] 

2.       My preference would be if you programmed to use our discovery layer’s [“Pika”] UserAPI. [for other options, see way way down below…]

 
3.       I have created two patron accounts. The barcode/PIN pairs are

a.       EXPIRED:      999018/7357

b.      ACTIVE:        999019/7357

 
4.       Currently, you probably only need one of the Pika UserAPI methods: validateAccount .

 
Example call:
https://catalog.library.nashville.org/API/UserAPI?method=getPatronProfile&username=999019&password=7357
 
Example response: (currently way too much info!)
{"result":{"success":true,"profile":{"id":"103649","source":"ils","username":"2089149","displayName":"R. Test","password":"","firstname":"Rabble Boombox","lastname":"Test","email":"james.staub@nashville.gov","phone":"","alt_username":null,"cat_username":"999019","cat_password":"7357","patronType":"0","created":"2016-04-28 00:00:00","homeLocationId":"24","myLocation1Id":"9","myLocation2Id":"25","trackReadingHistory":"0","initialReadingHistoryLoaded":"0","bypassAutoLogout":"0","disableRecommendations":"0","disableCoverArt":"0","overdriveEmail":"","promptForOverdriveEmail":"1","preferredLibraryInterface":null,"noPromptForUserReviews":"0","fullname":"Test, Rabble Boombox","address1":"","address2":", ","city":"","state":"","zip":"","workPhone":"","mobileNumber":"","web_note":"","expires":"12-31-37","expired":0,"expireClose":0,"fines":"$0.00","finesVal":0,"homeLocationCode":"mn","homeLocation":"Main Library","myLocation1":"Annex","myLocation2":"North","numCheckedOutIls":"0","numHoldsIls":0,"numHoldsAvailableIls":0,"numHoldsRequestedIls":0,"numCheckedOutEContent":null,"numHoldsEContent":null,"numHoldsAvailableEContent":null,"numHoldsRequestedEContent":null,"numCheckedOutOverDrive":0,"canUseOverDrive":true,"numHoldsOverDrive":0,"numHoldsAvailableOverDrive":0,"numHoldsRequestedOverDrive":0,"numBookings":0,"notices":"-","noticePreferenceLabel":"","numMaterialsRequests":0,"readingHistorySize":""}}}
 
5.       We can (and should) change the Pika UserAPI. FYI I have some initial questions about changing the API for this project at https://marmot.myjetbrains.com/youtrack/issue/PK-1871

 
6.       Our approach to providing access to online content is generally: we want to provide access to online content, regardless of the patron’s behavior with our tangible collection. Therefore the only data we care about in authorizing a patron to stream or download from the music collection is whether or not the account is expired. (And we don’t care about how much a patron owes in fines.) (We might care about patron age for some content… I’m gonna sidestep that issue for now)

 
[OTHER PATRON AUTHENTICATION OPTIONS]
 
My preference is that we use Pika’s UserAPI  – that way we can quickly change the API to provide needed responses, we won’t need to make a rabble-authentication-switch when we make our ILS switch, and we can bring on all the Schools patrons when they migrate to CARL.X in August 2016 with no additional work. But there are other options…
 
Currently, NPL uses III Millennium as our ILS. We are probably a week away from signing a contract with TLC for their CARL.X ILS, which should be implemented Jan 2017.
 
Starting with the latter: CARL.X has an extended SIP2 interface that probably will give and get everything you need.
 
Millennium’s SIP2 implementation ain’t the greatest, e.g., it does not allow for common extensions like providing patron email addresses in Patron Information Response (if I remember right).
III will charge us at least 1500 for allowing a connection with an additional SIP2 device; that being said, we should be able to simply use an extant SIP2 device’s login.
The preferred method of patron authentication/authorization/information retrieval with Millennium is the PatronAPI. If you have other potential library customers on Millennium or Sierra, it should be relatively easy for y’all to spin up code to send and parse responses from the PatronAPI.

**Comment by prestonaustin** [comment]
Closed. Reopen if we see errors after server port redirect alls-clear from me. Won't work til then.

**Comment by whblondeau** [comment]
CURRENT:
curl -v "http://localhost:5005/cardvalid?card_number=999019&card_pin=7357&collection=org.nashville.library.boombox"


EXPIRED:
curl -v "http://localhost:5005/cardvalid?card_number=999018&card_pin=7357&collection=org.nashville.library.boombox"
