### ISSUE TITLE
add R&B to genre categories in drop down box

### ISSUE THREAD

**Issue by kellyhiser** [therabble/nashville-public-library-client#23]
can this be done easily and quickly now? Request from the library

**Comment by prestonaustin** [comment]
@kellyhiser Should we make this custom per library, or change all to
include it? The list is not currently manageable content/config but will be
in the rewrite. I can move it to a default set and an optional variable to
change it in globals now fairly easily if we want custom per library now.

**Comment by kellyhiser** [comment]
custom per library is optimal.

**Comment by prestonaustin** [comment]
@kellyhiser 
Please add the desired item to this list as "R&B" or whatever string you want :)

  genreOptions : [
                   "Blues",
                   "Classical",
                   "Country",
                   "Dance & Electronic",
                   "Folk",
                   "Instrumental",
                   "Jazz",
                   "Pop",
                   "Rap & Hip Hop",
                   "Rock",
                   "Spiritual",
                   "World Music"
                 ]
});

**Comment by prestonaustin** [comment]
staged for next deploy
