### ISSUE TITLE
NBB records to delete (list in latest comment)

### ISSUE THREAD

**Issue by kellyhiser** [therabble/nashville-public-library-client#24]
Artist Al-D getting "Yikes" message when trying to access Complete Submission from Invite token

History on Al-D submission:
- I created a submission for Al-D along with 44 other real artists sometime the week of Sep 12
- I used that "sometime the week of Sep 12" Al-D submission to test whether invites would work properly, using my email on Monday or Tuesday of this week (I'm not totally certain of this timeline).
- I created a new Al-D submission sometime later in the week of Sep 12 to use for a real invite.
- I sent an invitation to Al-D at aldwords@gmail.com (along with all other 44 artists) on Friday Sep 16
- Al-D reported a Yikes! message to Ryan Tuesday Sep 20 in Chrome, but windows and mac
- I created a new submission (the third one for Al-D) on Sep 21 and sent to aldwords+taketwo@gmail.com as that kind of email fix has worked for other similar problems. he just reported that the Yikes message persists (Sep 22)
- I'm not sure that the third or second submission actually exist fully, as there is only one Al-D record in Complete Submission

@prestonaustin should I try creating yet another submission, with new title and artist name and email address and see if that works? this feels like a "this thing already exists and I'm barfing" kind of problem

**Comment by kellyhiser** [comment]
Mystery Twin invite sent to the wrong email address because typo, so let's delete and I'll generate new invitations for both them and Al-D

**Comment by kellyhiser** [comment]
Delete the follow albums/artists that are published in production: 
- [ ] Coffee Please by Blue Truck
- [ ] Floral Couch by Norman the Cat
- [ ]  Iffy Writ by Walker Evans
- [ ] Demo by Circle Vs El

Delete all records (because invitation emails were lost) OR recover invitation token urls (if easy and quick to do so) for the following artists (all album titles are "Album"): 
- [ ] Stacy Mitchhart (invitation sent to gina@thegalaxieagency.com)
- [ ] Mystery Twins (invitation sent to doug.legmann@gmail.com)

Maybe delete (I'm waiting to hear whether they checked the correct email account - fine to delete before I have an answer if that's easier than not deleting and then needing to delete later):
- [ ] Doug Moser and Jonathan Estes (invitation sent to: estesbass@gmail.com)

Maybe delete depending on Preston/Bill answer to #29:
- [ ] Rain Came Down by Leah Grams Johnson
- [ ] When the Bough Breaks by [Leah Grams Johnson]

**Comment by whblondeau** [comment]
@kellyhiser we're going to delete Rain Comes Down.
