### ISSUE TITLE
delete artists and albums who did not respond to their invitations

### ISSUE THREAD

**Issue by kellyhiser** [therabble/nashville-public-library-client#34]
Ryan wants to delete records for artists who did not respond to invitations so that he can have a handle on the budget. He knows that if artists do try to complete submissions after their records have been deleted they will get some kind of error message. He's fine with that, and with fielding responses (and he's already informed artists they've passed a deadline for completing submissions). Might as well clear out a couple new test records as well.

Here's the list of Artists to delete (albums = "Album" unless specified):
- [x] Anna Wilson
- [x] Billy Ramirez
- [x] Buzz Cason
- [x] Chill Witch
- [x] Kelly October Test (album: October Test)
- [x] Marcela Pinella
- [x] Mike Floss
- [x] OJR
- [x] Preston, mostly (album: Hennepin Demo Tracks)
- [x] Pretty Fall Artist (album: Pretty Fall Day)
- [x] Sarah Gayle Meech
- [x] Sexx
- [x] Stacy Mitchhart

**Comment by prestonaustin** [comment]
Bill is deleting all of these now, Preston is standing by to address any issues that may bring up in production (none are expected)

**Comment by whblondeau** [comment]
Done. No difficulties, no noted problems.

NB Marcela Pinella's first name was misspelled in the slug. (at least I _think_ it was wrong in the slug: I believe "Marcela" with one L is correct.)

"records marked for deletion:
org.nashville.library.boombox:/complete-submission/albums/boombox-fall-2016/marcella-pinella-album"

**Comment by whblondeau** [comment]
I kept a text log of deleted records, including the users which were not deleted, merely flagged for references. Stashed it serverside as /var/www/deploy-scriptlogs/20161006_deletions.txt
