### ISSUE TITLE
Update footer graphic hyperlink to library.nashville.org 

### ISSUE THREAD

**Issue by kellyhiser** [therabble/nashville-public-library-client#38]
@prestonaustin please review that to do this I should update presentingURL here: https://github.com/therabble/musicat-namespaces/blob/master/org.nashville.library_authority/org.nashville.library.boombox_ns/org.nashville.library.boombox_files/app/services/musicat-global.js

and here: https://github.com/therabble/musicat-namespaces/blob/master/org.nashville.library_authority/org.nashville.library.boombox_ns/org.nashville.library.boombox_files/config/environment.js

**Comment by prestonaustin** [comment]
Kelly, that's correct. N.B. Eventually environment.js will be entirely deprecated for this sort of thing, so don't add things there you don't find there already.

See comments about how to close and reference PRs here if you haven't https://github.com/therabble/nashville-public-library-client/issues/35#issuecomment-255531719

**Comment by kellyhiser** [comment]
Okay, I fucked up the PR - issue protocol @prestonaustin outlined in #35 in an attempt to create multiple PRs on the same branch. Sorry :/ 

What I did: changed presentingUrl in musicat-global.js on the NBB-Open-Submissions branch here https://github.com/therabble/musicat-namespaces/blob/NBB-open-submissions/org.nashville.library_authority/org.nashville.library.boombox_ns/org.nashville.library.boombox_files/app/services/musicat-global.js 

I couldn't find presenting Url in enviroment.js
