### ISSUE TITLE
change banner text to advertise NBB open submissions

### ISSUE THREAD

**Issue by kellyhiser** [therabble/nashville-public-library-client#40]
replace text for artist banner with submissions info 

Join Us
Have your music reviewed for BoomBox by our Guest Curator 
Submit

@prestonaustin please review whether I can do this by replacing text here: https://github.com/therabble/musicat-namespaces/blob/master/org.nashville.library_authority/org.nashville.library.boombox_ns/org.nashville.library.boombox_files/app/services/musicat-global.js

**Comment by prestonaustin** [comment]
Kelly - yep, that's correct. Be careful about commas between entries or blocks in lists, and don't add one after the last if there isn't one there in lists in .json and .js files.

See comments about how to close and reference PRs here if you haven't https://github.com/therabble/nashville-public-library-client/issues/35#issuecomment-255531719

**Comment by kellyhiser** [comment]
closed by https://github.com/therabble/musicat-namespaces/pull/6
