### ISSUE TITLE
Create artist FAQ

### ISSUE THREAD

**Issue by lahollen** [therabble/nashville-public-library-client#9]
Create a FAQ document for artists about submission process and licensing.

**Comment by kellyhiser** [comment]
Capital City Records FAQ here: https://capitalcityrecords.ca/faq
YML musicians' FAQ: 
[yahara_musicians_FAQ_2016.pdf](https://github.com/therabble/nashville-public-library-client/files/186215/yahara_musicians_FAQ_2016.pdf)
